version: 0.2
#AWS Pipeline CodeBuild: Client

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm run install:client
  build:
    commands:
      - npm run build:client

artifacts:
  base-directory: "./webapp/dist/"
  files:
    - "**/*"
